# Generated by Django 5.0.1 on 2025-12-31 23:55

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'users_otp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach'), ('admin', 'Admin')], default='athlete', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='CoachVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('coach_message', models.TextField(blank=True, help_text='Message from coach about their qualifications')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of coaching specializations')),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of coaching experience')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach Verification Request',
                'verbose_name_plural': 'Coach Verification Requests',
                'db_table': 'users_coach_verification_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('daily_date', models.DateField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP Rate Limit',
                'verbose_name_plural': 'OTP Rate Limits',
                'db_table': 'users_otp_ratelimit',
                'unique_together': {('phone', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'ID Card'), ('certificate', 'Certificate'), ('license', 'License'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to=users.models.verification_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('original_filename', models.CharField(blank=True, help_text='Original uploaded filename', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.coachverificationrequest')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'db_table': 'users_verification_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='users.coachverificationrequest')),
            ],
            options={
                'verbose_name': 'Verification Status Log',
                'verbose_name_plural': 'Verification Status Logs',
                'db_table': 'users_verification_status_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
