# Generated by Django 5.0.1 on 2026-01-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachverificationrequest',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active verification request is allowed per coach'),
        ),
    ]
