# Generated by Django 5.0.1 on 2026-01-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coachverificationrequest_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='coachverificationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_verification_per_coach'),
        ),
    ]
