# Generated by Django 5.0.1 on 2026-01-04 13:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_verificationdocument_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachverificationrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='otpratelimit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verificationdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verificationstatuslog',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.12'), help_text='Platform commission rate (0.12 = 12%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='coachverificationrequest',
            name='coach_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coachverificationrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coachverificationrequest',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='coachverificationrequest',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(max_length=30),
        ),
    ]
