# Generated by Django 5.0.1 on 2026-01-05 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('token_created', 'Token Created'), ('token_used', 'Token Used'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('bypass_attempt', 'Bypass Attempt'), ('token_tampered', 'Token Tampered')], max_length=50)),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_summary', models.JSONField(default=dict)),
                ('result', models.CharField(max_length=50)),
                ('gross_amount', models.BigIntegerField(blank=True, null=True)),
                ('commission_amount', models.BigIntegerField(blank=True, null=True)),
                ('net_amount', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('entry_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_commission_config',
            },
        ),
        migrations.CreateModel(
            name='TrustToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_id', models.UUIDField()),
                ('coach_id', models.UUIDField()),
                ('athlete_id', models.UUIDField()),
                ('gross_amount', models.BigIntegerField()),
                ('commission_amount', models.BigIntegerField()),
                ('net_amount', models.BigIntegerField()),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('integrity_hash', models.CharField(blank=True, max_length=64)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('used_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_trust_token',
            },
        ),
        migrations.CreateModel(
            name='DisintermediationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disint_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_disintermediation_alert',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.BigIntegerField()),
                ('commission_amount', models.BigIntegerField()),
                ('net_amount', models.BigIntegerField()),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('trust_token', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='billing.trusttoken')),
            ],
            options={
                'db_table': 'billing_payout',
            },
        ),
    ]
