# Generated by Django 5.0.1 on 2026-01-05 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('token_created', 'Token Created'), ('token_used', 'Token Used'), ('token_expired', 'Token Expired'), ('token_validation_failed', 'Token Validation Failed'), ('payout_initiated', 'Payout Initiated'), ('payout_created', 'Payout Created'), ('payout_completed', 'Payout Completed'), ('payout_failed', 'Payout Failed'), ('bypass_attempt', 'Bypass Attempt'), ('token_tampered', 'Token Tampered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='result',
            field=models.CharField(default='success', max_length=50),
        ),
        migrations.AlterField(
            model_name='disintermediationalert',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payout',
            name='coach',
            field=models.ForeignKey(blank=True, db_column='coach_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trusttoken',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
