# Generated by Django 5.0.1 on 2026-01-06 14:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthletePreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_goal', models.CharField(choices=[('weight_loss', 'کاهش وزن'), ('muscle_gain', 'افزایش عضله'), ('strength', 'افزایش قدرت'), ('endurance', 'استقامت'), ('flexibility', 'انعطاف\u200cپذیری'), ('competition', 'آمادگی مسابقه'), ('general_fitness', 'تناسب اندام عمومی'), ('rehabilitation', 'توانبخشی')], default='general_fitness', max_length=50)),
                ('secondary_goals', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(choices=[('beginner', 'مبتدی (کمتر از ۶ ماه)'), ('intermediate', 'متوسط (۶ ماه تا ۲ سال)'), ('advanced', 'پیشرفته (۲ تا ۵ سال)'), ('professional', 'حرفه\u200cای (بیش از ۵ سال)')], default='beginner', max_length=20)),
                ('training_days_per_week', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('has_gym_access', models.BooleanField(default=True)),
                ('has_home_equipment', models.BooleanField(default=False)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)])),
                ('height_cm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('preferred_coach_gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('no_preference', 'فرقی نمی\u200cکند')], default='no_preference', max_length=20)),
                ('max_budget', models.BigIntegerField(blank=True, null=True)),
                ('preferred_city', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(default='fa', max_length=50)),
                ('injuries', models.JSONField(blank=True, default=list)),
                ('medical_conditions', models.JSONField(blank=True, default=list)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('quiz_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athlete Preferences',
                'verbose_name_plural': 'Athlete Preferences',
                'db_table': 'matching_athlete_preferences',
            },
        ),
        migrations.CreateModel(
            name='MatchingInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view_profile', 'View Profile'), ('click_program', 'Click Program'), ('start_message', 'Start Message'), ('purchase', 'Purchase'), ('skip', 'Skip'), ('save', 'Save'), ('report', 'Report')], max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('match_score_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_interactions', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_interaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['athlete', 'action', '-created_at'], name='matching_in_athlete_a6bdcb_idx'), models.Index(fields=['coach', 'action', '-created_at'], name='matching_in_coach_i_c2f7b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('reasons', models.JSONField(default=list)),
                ('was_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('was_clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('resulted_in_purchase', models.BooleanField(default=False)),
                ('purchase_at', models.DateTimeField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_match_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['athlete', '-score'], name='matching_ma_athlete_b0fced_idx'), models.Index(fields=['coach', '-created_at'], name='matching_ma_coach_i_b76906_idx')],
            },
        ),
    ]
