# Generated by Django 5.0.1 on 2026-01-06 14:53

import django.core.validators
import django.db.models.deletion
import programs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_auditlog_details_auditlog_target_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('category', models.CharField(choices=[('weight_loss', 'کاهش وزن'), ('muscle_gain', 'عضله\u200cسازی'), ('strength', 'قدرتی'), ('endurance', 'استقامت'), ('flexibility', 'انعطاف\u200cپذیری'), ('competition_prep', 'آمادگی مسابقه'), ('general_fitness', 'تناسب اندام عمومی'), ('rehabilitation', 'توانبخشی'), ('nutrition', 'تغذیه'), ('hybrid', 'ترکیبی')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('professional', 'حرفه\u200cای')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('duration_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('sessions_per_week', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('price_toman', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price_toman', models.BigIntegerField(blank=True, help_text='Original price before discount', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=programs.models.program_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('pdf_file_hash', models.CharField(blank=True, max_length=64)),
                ('pdf_page_count', models.PositiveIntegerField(default=0)),
                ('preview_images', models.JSONField(blank=True, default=list)),
                ('preview_video_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار بررسی'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده'), ('rejected', 'رد شده')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programs_program',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_paid_toman', models.BigIntegerField()),
                ('commission_amount', models.BigIntegerField(default=0)),
                ('net_amount', models.BigIntegerField(default=0)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.12, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('delivered', 'تحویل داده شده'), ('refunded', 'بازپرداخت شده'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(default=5)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_download_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_purchases', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='programs.program')),
                ('trust_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_purchase', to='billing.trusttoken')),
            ],
            options={
                'db_table': 'programs_purchase',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='programs.purchase')),
            ],
            options={
                'db_table': 'programs_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('bound_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('used_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_user_agent', models.TextField(blank=True)),
                ('used_user_agent', models.TextField(blank=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='programs.purchase')),
            ],
            options={
                'db_table': 'programs_download_token',
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['coach', 'status'], name='programs_pr_coach_i_f663f2_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['category', 'difficulty'], name='programs_pr_categor_7c4b80_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['price_toman'], name='programs_pr_price_t_3f6f55_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['status', 'is_featured'], name='programs_pr_status_e2a6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['created_at'], name='programs_pr_created_57e113_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['athlete', 'status'], name='programs_pu_athlete_5d9a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['program', 'status'], name='programs_pu_program_58ae46_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['created_at'], name='programs_pu_created_834b7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'paid', 'delivered'])), fields=('athlete', 'program'), name='unique_active_purchase'),
        ),
        migrations.AddConstraint(
            model_name='programreview',
            constraint=models.UniqueConstraint(fields=('purchase',), name='one_review_per_purchase'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['token_hash', 'status'], name='programs_do_token_h_5acc4b_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['purchase', 'status'], name='programs_do_purchas_0c71c7_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['expires_at'], name='programs_do_expires_f89756_idx'),
        ),
    ]
