# Generated by Django 5.0.1 on 2026-01-06 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('search_type', models.CharField(choices=[('coach', 'Coach Search'), ('program', 'Program Search'), ('general', 'General Search')], default='coach', max_length=20)),
                ('query_text', models.CharField(blank=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('sort_by', models.CharField(blank=True, default='relevance', max_length=50)),
                ('notify_new_results', models.BooleanField(default=False)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('last_result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'db_table': 'search_saved',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_type', models.CharField(choices=[('coach', 'Coach Search'), ('program', 'Program Search'), ('general', 'General Search')], default='general', max_length=20)),
                ('query_text', models.CharField(blank=True, max_length=255)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('sort_by', models.CharField(blank=True, max_length=50)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('result_ids', models.JSONField(blank=True, default=list)),
                ('clicked_result_id', models.UUIDField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'db_table': 'search_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=255)),
                ('query_normalized', models.CharField(db_index=True, max_length=255)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'db_table': 'search_query',
                'ordering': ['-search_count', '-last_searched_at'],
                'indexes': [models.Index(fields=['query_normalized'], name='search_quer_query_n_007e8a_idx'), models.Index(fields=['-search_count'], name='search_quer_search__9aa065_idx'), models.Index(fields=['category', '-search_count'], name='search_quer_categor_ca7237_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_saved_search_name'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user', '-created_at'], name='search_log_user_id_e36ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['search_type', '-created_at'], name='search_log_search__542a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['session_id'], name='search_log_session_53cc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['-created_at'], name='search_log_created_e094e8_idx'),
        ),
    ]
